export const R2_BASE_URL = 'https://pub-296ac8e5f201453fbddfdbd8902dad2f.r2.dev/';

export const TRACKS = [
  {
    id: '1',
    title: 'Drift',
    titleAr: 'انجراف',
    description: 'Float into deep relaxation',
    descriptionAr: 'انجرف نحو استرخاء عميق',
    file: 'drift.mp3',
    category: 'relax',
    emoji: '🌊',
    hz: '432 Hz',
    benefit: 'Reduces anxiety and stress, harmonizes the body with nature\'s rhythm',
    benefitAr: 'يقلل القلق والتوتر، ويوافق الجسم مع إيقاع الطبيعة',
    timeOfDay: 'night',
  },
  {
    id: '2',
    title: 'Joy',
    titleAr: 'بهجة',
    description: 'Uplift your spirit with healing frequencies',
    descriptionAr: 'ارفع روحك بالترددات الشفائية',
    file: 'joy.mp3',
    category: 'energy',
    emoji: '✨',
    hz: '528 Hz',
    benefit: 'Known as the "Miracle Tone" — promotes DNA repair, transformation and joy',
    benefitAr: 'يُعرف بـ "نغمة المعجزة" — يعزز إصلاح الحمض النووي والتحول والبهجة',
    timeOfDay: 'morning',
  },
  {
    id: '3',
    title: 'Reset',
    titleAr: 'إعادة ضبط',
    description: 'Clear your energy and start fresh',
    descriptionAr: 'امسح طاقتك وابدأ من جديد',
    file: 'reset.mp3',
    category: 'clear',
    emoji: '🔄',
    hz: '396 Hz',
    benefit: 'Liberates fear and guilt, clears mental blocks and helps achieve goals',
    benefitAr: 'يحرر الخوف والذنب، يزيل العوائق الذهنية ويساعد على تحقيق الأهداف',
    timeOfDay: 'morning',
  },
  {
    id: '4',
    title: 'For Love',
    titleAr: 'من أجل الحب',
    description: 'Open your heart to unconditional love',
    descriptionAr: 'افتح قلبك للحب غير المشروط',
    file: 'for-love.mp3',
    category: 'heart',
    emoji: '💜',
    hz: '639 Hz',
    benefit: 'Enhances communication, understanding and harmonizes relationships',
    benefitAr: 'يعزز التواصل والتفاهم وينسجم العلاقات الإنسانية',
    timeOfDay: 'any',
  },
  {
    id: '5',
    title: 'Deep Focus',
    titleAr: 'تركيز عميق',
    description: 'Enter a state of laser-sharp focus',
    descriptionAr: 'ادخل في حالة من التركيز الحاد',
    file: 'deep-focus.mp3',
    category: 'focus',
    emoji: '🎯',
    hz: '40 Hz',
    benefit: 'Gamma waves — enhances cognitive function, memory and concentration',
    benefitAr: 'موجات غاما — تعزز الوظائف المعرفية والذاكرة والتركيز',
    timeOfDay: 'morning',
  },
  {
    id: '6',
    title: 'Back to Center',
    titleAr: 'العودة للمركز',
    description: 'Return to your inner stillness',
    descriptionAr: 'عد إلى سكونك الداخلي',
    file: 'back-to-center.mp3',
    category: 'balance',
    emoji: '⚖️',
    hz: '528 Hz',
    benefit: 'Restores inner balance and harmony, promotes healing and positive change',
    benefitAr: 'يستعيد التوازن الداخلي والانسجام، يعزز الشفاء والتغيير الإيجابي',
    timeOfDay: 'any',
  },
  {
    id: '7',
    title: 'Quietly',
    titleAr: 'بهدوء',
    description: 'Find peace in the silence between sounds',
    descriptionAr: 'اجد السلام في صمت بين الأصوات',
    file: 'quietly.mp3',
    category: 'peace',
    emoji: '🌙',
    hz: '174 Hz',
    benefit: 'Foundation frequency — relieves pain and stress, brings deep sense of security',
    benefitAr: 'تردد الأساس — يخفف الألم والتوتر، يمنح شعوراً عميقاً بالأمان',
    timeOfDay: 'night',
  },
  {
    id: '8',
    title: 'Creative Space',
    titleAr: 'الفضاء الإبداعي',
    description: 'Unlock your limitless creative potential',
    descriptionAr: 'أطلق إمكاناتك الإبداعية اللامحدودة',
    file: 'creative-space.mp3',
    category: 'energy',
    emoji: '🎨',
    hz: '852 Hz',
    benefit: 'Awakens intuition and returns to spiritual order, expands creativity',
    benefitAr: 'يوقظ الحدس ويعيد إلى النظام الروحي، ويوسع الإبداع',
    timeOfDay: 'morning',
  },
  {
    id: '9',
    title: 'Deep Peace',
    titleAr: 'سلام عميق',
    description: 'Sink into profound peace and stillness',
    descriptionAr: 'انغمس في سلام عميق وهدوء',
    file: 'deep-peace.mp3',
    category: 'peace',
    emoji: '🕊️',
    hz: '285 Hz',
    benefit: 'Influences energy fields, promotes cellular rejuvenation and deep healing',
    benefitAr: 'يؤثر في المجالات الطاقية، يعزز تجديد الخلايا والشفاء العميق',
    timeOfDay: 'night',
  },
  {
    id: '10',
    title: 'This Moment',
    titleAr: 'هذه اللحظة',
    description: 'Be fully present in the now',
    descriptionAr: 'كن حاضراً تماماً في اللحظة الراهنة',
    file: 'this-moment.mp3',
    category: 'mindful',
    emoji: '🌸',
    hz: '963 Hz',
    benefit: 'Highest Solfeggio frequency — activates the pineal gland and divine consciousness',
    benefitAr: 'أعلى ترددات سولفيجيو — ينشط الغدة الصنوبرية ويتصل بالوعي الإلهي',
    timeOfDay: 'any',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All', labelAr: 'الكل' },
  { id: 'relax', label: 'Relax', labelAr: 'استرخاء' },
  { id: 'focus', label: 'Focus', labelAr: 'تركيز' },
  { id: 'energy', label: 'Energy', labelAr: 'طاقة' },
  { id: 'peace', label: 'Peace', labelAr: 'سلام' },
  { id: 'heart', label: 'Heart', labelAr: 'قلب' },
  { id: 'balance', label: 'Balance', labelAr: 'توازن' },
  { id: 'clear', label: 'Clear', labelAr: 'تنقية' },
  { id: 'mindful', label: 'Mindful', labelAr: 'يقظة' },
];

export const getTrackUrl = (file) => `${R2_BASE_URL}${file}`;
