export const R2_BASE_URL = 'https://pub-296ac8e5f201453fbddfdbd8902dad2f.r2.dev/';

export const TRACKS = [
  {
    id: '1',
    title: 'Drift',
    titleAr: 'انجراف',
    description: 'Surrender to the current — let the water carry you home',
    descriptionAr: 'استسلم للتيار، دع الماء يحملك نحو الوطن',
    file: 'drift.mp3',
    category: 'relax',
    emoji: '🌊',
    trackColor: ['#0ea5e9', '#0369a1'],
    hz: '432 Hz',
    benefit: 'Reduces anxiety and stress, harmonizes the body with nature\'s rhythm',
    benefitAr: 'يقلل القلق والتوتر، ويوافق الجسم مع إيقاع الطبيعة',
    timeOfDay: 'night',
  },
  {
    id: '2',
    title: 'Joy',
    titleAr: 'بهجة',
    description: 'The miracle tone — let joy bloom from deep within',
    descriptionAr: 'تردد المعجزة — دع الفرح يتفتح من أعماقك',
    file: 'joy.mp3',
    category: 'energy',
    emoji: '✨',
    trackColor: ['#f59e0b', '#b45309'],
    hz: '528 Hz',
    benefit: 'Known as the "Miracle Tone" — promotes DNA repair, transformation and joy',
    benefitAr: 'يُعرف بـ "نغمة المعجزة" — يعزز إصلاح الحمض النووي والتحول والبهجة',
    timeOfDay: 'morning',
  },
  {
    id: '3',
    title: 'Reset',
    titleAr: 'إعادة ضبط',
    description: 'Release what no longer serves you — return to clarity',
    descriptionAr: 'أطلق ما لم يعد يخدمك، وعد إلى الصفاء',
    file: 'reset.mp3',
    category: 'clear',
    emoji: '🌀',
    trackColor: ['#22c55e', '#15803d'],
    hz: '396 Hz',
    benefit: 'Liberates fear and guilt, clears mental blocks and helps achieve goals',
    benefitAr: 'يحرر الخوف والذنب، يزيل العوائق الذهنية ويساعد على تحقيق الأهداف',
    timeOfDay: 'morning',
  },
  {
    id: '4',
    title: 'For Love',
    titleAr: 'من أجل الحب',
    description: 'Open every door of your heart — love flows freely',
    descriptionAr: 'افتح كل أبواب قلبك، الحب يتدفق بحرية',
    file: 'for-love.mp3',
    category: 'heart',
    emoji: '💗',
    trackColor: ['#ec4899', '#be185d'],
    hz: '639 Hz',
    benefit: 'Enhances communication, understanding and harmonizes relationships',
    benefitAr: 'يعزز التواصل والتفاهم وينسجم العلاقات الإنسانية',
    timeOfDay: 'any',
  },
  {
    id: '5',
    title: 'Deep Focus',
    titleAr: 'تركيز عميق',
    description: 'Enter the gamma state — where your mind becomes infinite',
    descriptionAr: 'ادخل حالة غاما، حيث عقلك يصبح لا نهائياً',
    file: 'deep-focus.mp3',
    category: 'focus',
    emoji: '💎',
    trackColor: ['#6366f1', '#3730a3'],
    hz: '40 Hz',
    benefit: 'Gamma waves — enhances cognitive function, memory and concentration',
    benefitAr: 'موجات غاما — تعزز الوظائف المعرفية والذاكرة والتركيز',
    timeOfDay: 'morning',
  },
  {
    id: '6',
    title: 'Back to Center',
    titleAr: 'العودة للمركز',
    description: 'Find the still point at the center of everything',
    descriptionAr: 'اعثر على نقطة السكون في مركز كل شيء',
    file: 'back-to-center.mp3',
    category: 'balance',
    emoji: '☯️',
    trackColor: ['#14b8a6', '#0f766e'],
    hz: '528 Hz',
    benefit: 'Restores inner balance and harmony, promotes healing and positive change',
    benefitAr: 'يستعيد التوازن الداخلي والانسجام، يعزز الشفاء والتغيير الإيجابي',
    timeOfDay: 'any',
  },
  {
    id: '7',
    title: 'Quietly',
    titleAr: 'بهدوء',
    description: 'In the silence between breaths — you are whole',
    descriptionAr: 'في الصمت بين أنفاسك، أنت كامل',
    file: 'quietly.mp3',
    category: 'peace',
    emoji: '🌙',
    trackColor: ['#8b5cf6', '#5b21b6'],
    hz: '174 Hz',
    benefit: 'Foundation frequency — relieves pain and stress, brings deep sense of security',
    benefitAr: 'تردد الأساس — يخفف الألم والتوتر، يمنح شعوراً عميقاً بالأمان',
    timeOfDay: 'night',
  },
  {
    id: '8',
    title: 'Creative Space',
    titleAr: 'الفضاء الإبداعي',
    description: 'Your imagination knows no boundaries — expand into the cosmos',
    descriptionAr: 'خيالك لا حدود له — توسّع نحو الكون',
    file: 'creative-space.mp3',
    category: 'energy',
    emoji: '🌌',
    trackColor: ['#f97316', '#c2410c'],
    hz: '852 Hz',
    benefit: 'Awakens intuition and returns to spiritual order, expands creativity',
    benefitAr: 'يوقظ الحدس ويعيد إلى النظام الروحي، ويوسع الإبداع',
    timeOfDay: 'morning',
  },
  {
    id: '9',
    title: 'Deep Peace',
    titleAr: 'سلام عميق',
    description: 'Sink beneath the noise — into the infinite ocean of peace',
    descriptionAr: 'انغمس تحت الضجيج، في محيط السلام اللانهائي',
    file: 'deep-peace.mp3',
    category: 'peace',
    emoji: '🕊️',
    trackColor: ['#a78bfa', '#7c3aed'],
    hz: '285 Hz',
    benefit: 'Influences energy fields, promotes cellular rejuvenation and deep healing',
    benefitAr: 'يؤثر في المجالات الطاقية، يعزز تجديد الخلايا والشفاء العميق',
    timeOfDay: 'night',
  },
  {
    id: '10',
    title: 'This Moment',
    titleAr: 'هذه اللحظة',
    description: 'This breath. This heartbeat. This is enough.',
    descriptionAr: 'هذا النَّفَس. هذه النبضة. هذا كافٍ.',
    file: 'this-moment.mp3',
    category: 'mindful',
    emoji: '🌸',
    trackColor: ['#f9a8d4', '#db2777'],
    hz: '963 Hz',
    benefit: 'Highest Solfeggio frequency — activates the pineal gland and divine consciousness',
    benefitAr: 'أعلى ترددات سولفيجيو — ينشط الغدة الصنوبرية ويتصل بالوعي الإلهي',
    timeOfDay: 'any',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All', labelAr: 'الكل' },
  { id: 'relax', label: 'Relax', labelAr: 'استرخاء' },
  { id: 'focus', label: 'Focus', labelAr: 'تركيز' },
  { id: 'energy', label: 'Energy', labelAr: 'طاقة' },
  { id: 'peace', label: 'Peace', labelAr: 'سلام' },
  { id: 'heart', label: 'Heart', labelAr: 'قلب' },
  { id: 'balance', label: 'Balance', labelAr: 'توازن' },
  { id: 'clear', label: 'Clear', labelAr: 'تنقية' },
  { id: 'mindful', label: 'Mindful', labelAr: 'يقظة' },
];

const GITHUB_AUDIO = 'https://raw.githubusercontent.com/soubaiazahouse-svg/detox-your-path/claude/aza-audio-playback-eas-lsyo27/guided-audio/';

export const GUIDED_SESSIONS = [
  {
    id: 'g1',
    title: 'Sleep Journey',
    titleAr: 'رحلة النوم',
    description: 'A guided journey into deep restful sleep',
    descriptionAr: 'رحلة صوتية موجهة نحو نوم عميق ومريح',
    file: `${GITHUB_AUDIO}guided-sleep.mp3`,
    emoji: '🌙',
    trackColor: ['#1e1b4b', '#312e81'],
    duration: '11 min',
    durationAr: '١١ دقيقة',
  },
  {
    id: 'g2',
    title: 'Morning Awakening',
    titleAr: 'يقظة الصباح',
    description: 'Activate your mind and body for a powerful day',
    descriptionAr: 'نشّط عقلك وجسدك ليوم مليء بالطاقة',
    file: `${GITHUB_AUDIO}guided-wake.mp3`,
    emoji: '☀️',
    trackColor: ['#78350f', '#92400e'],
    duration: '28 min',
    durationAr: '٢٨ دقيقة',
  },
];

export const getTrackUrl = (file) =>
  file.startsWith('http') ? file : `${R2_BASE_URL}${file}`;
