export const R2_BASE_URL = 'https://pub-296ac8e5f201453fbddfdbd8902dad2f.r2.dev/';

export const TRACKS = [
  {
    id: '1',
    title: 'Drift',
    titleAr: 'انجراف',
    description: 'Float into deep relaxation',
    descriptionAr: 'انجرف نحو استرخاء عميق',
    file: 'drift.mp3',
    category: 'relax',
    emoji: '🌊',
  },
  {
    id: '2',
    title: 'Joy',
    titleAr: 'بهجة',
    description: 'Uplift your spirit with healing frequencies',
    descriptionAr: 'ارفع روحك بالترددات الشفائية',
    file: 'joy.mp3',
    category: 'energy',
    emoji: '✨',
  },
  {
    id: '3',
    title: 'Reset',
    titleAr: 'إعادة ضبط',
    description: 'Clear your energy and start fresh',
    descriptionAr: 'امسح طاقتك وابدأ من جديد',
    file: 'reset.mp3',
    category: 'clear',
    emoji: '🔄',
  },
  {
    id: '4',
    title: 'For Love',
    titleAr: 'من أجل الحب',
    description: 'Open your heart to unconditional love',
    descriptionAr: 'افتح قلبك للحب غير المشروط',
    file: 'for-love.mp3',
    category: 'heart',
    emoji: '💜',
  },
  {
    id: '5',
    title: 'Deep Focus',
    titleAr: 'تركيز عميق',
    description: 'Enter a state of laser-sharp focus',
    descriptionAr: 'ادخل في حالة من التركيز الحاد',
    file: 'deep-focus.mp3',
    category: 'focus',
    emoji: '🎯',
  },
  {
    id: '6',
    title: 'Back to Center',
    titleAr: 'العودة للمركز',
    description: 'Return to your inner stillness',
    descriptionAr: 'عد إلى سكونك الداخلي',
    file: 'back-to-center.mp3',
    category: 'balance',
    emoji: '⚖️',
  },
  {
    id: '7',
    title: 'Quietly',
    titleAr: 'بهدوء',
    description: 'Find peace in the silence between sounds',
    descriptionAr: 'اجد السلام في صمت بين الأصوات',
    file: 'quietly.mp3',
    category: 'peace',
    emoji: '🌙',
  },
  {
    id: '8',
    title: 'Creative Space',
    titleAr: 'الفضاء الإبداعي',
    description: 'Unlock your limitless creative potential',
    descriptionAr: 'أطلق إمكاناتك الإبداعية اللامحدودة',
    file: 'creative-space.mp3',
    category: 'energy',
    emoji: '🎨',
  },
  {
    id: '9',
    title: 'Deep Peace',
    titleAr: 'سلام عميق',
    description: 'Sink into profound peace and stillness',
    descriptionAr: 'انغمس في سلام عميق وهدوء',
    file: 'deep-peace.mp3',
    category: 'peace',
    emoji: '🕊️',
  },
  {
    id: '10',
    title: 'This Moment',
    titleAr: 'هذه اللحظة',
    description: 'Be fully present in the now',
    descriptionAr: 'كن حاضراً تماماً في اللحظة الراهنة',
    file: 'this-moment.mp3',
    category: 'mindful',
    emoji: '🌸',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All', labelAr: 'الكل' },
  { id: 'relax', label: 'Relax', labelAr: 'استرخاء' },
  { id: 'focus', label: 'Focus', labelAr: 'تركيز' },
  { id: 'energy', label: 'Energy', labelAr: 'طاقة' },
  { id: 'peace', label: 'Peace', labelAr: 'سلام' },
  { id: 'heart', label: 'Heart', labelAr: 'قلب' },
  { id: 'balance', label: 'Balance', labelAr: 'توازن' },
  { id: 'clear', label: 'Clear', labelAr: 'تنقية' },
  { id: 'mindful', label: 'Mindful', labelAr: 'يقظة' },
];

export const getTrackUrl = (file) => `${R2_BASE_URL}${file}`;
